### ISSUE TITLE
Ошибка при открытии обработки

### ISSUE THREAD

**Issue by Sbenik** [vandalsvq/1c_code_diff#5]
Конфа УТиВСК (CRM) версии 11.5.8.287. Платформа 8.3.20.1674.  Ошибка при открытии на скрине.
![image](https://user-images.githubusercontent.com/41571399/221479077-7404f8bc-88de-427d-a1f1-57855e71e7eb.png)

**Comment by vandalsvq** [comment]
закрыт в 1.3
